name: 'Build and Deploy Application'

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  PROJECT_ID: ron-test-2025
  GCR_LOCATION: us-central1
  SERVICE: health-webapp
  REGION: us-central1

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        pytest --cov=app --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Docker Auth
      run: |-
        gcloud auth configure-docker "${{ env.GCR_LOCATION }}-docker.pkg.dev"

    - name: Build and Push Container
      run: |-
        docker build -t "${{ env.GCR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/health-webapp/${{ env.SERVICE }}:${{ github.sha }}" ./
        docker push "${{ env.GCR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/health-webapp/${{ env.SERVICE }}:${{ github.sha }}"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --image ${{ env.GCR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/health-webapp/${{ env.SERVICE }}:${{ github.sha }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated
